### PR TITLE
fix(baremetal): unexpected reinstall on ssh key ids changes

### LINKED ISSUE #1542: Baremetal: unexpected reinstall on ssh_key_ids change
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_baremetal_server

### Terraform Configuration Files

```hcl
resource scaleway_baremetal_server server {
  ssh_key_ids = ["0a53dbc9-c5e7-4857-b0a8-d03553844dc2"]
  offer       = "EM-B112X-SSD"
  os          = "96e5f0f2-d216-4de2-8a15-68730d877885"
}
```

### Debug Output

```
  # scaleway_baremetal_server.server will be updated in-place
  ~ resource "scaleway_baremetal_server" "server" {
        id              = "fr-par-2/3db70fbd-909f-4396-ad91-d729a1a3b418"
        name            = "tf-bm-inspiring-shockley"
      ~ ssh_key_ids     = [
          - "677fbba6-4e66-4861-b735-d04d196cd657",
          + "0a53dbc9-c5e7-4857-b0a8-d03553844dc2",
        ]
        tags            = []
        # (9 unchanged attributes hidden)
    }

```

### Expected Behavior

A state update as seen in output

### Actual Behavior

Server is reinstalled without warning

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by yfodil**
fix #1542

### CODE REVIEW

File: scaleway/helpers_baremetal.go [hunk 1]
```diff
@@ -133,3 +134,15 @@ func waitForBaremetalServerInstall(ctx context.Context, api *baremetal.API, zone
 
 	return server, err
 }
+
+func baremetalInstallServer(ctx context.Context, d *schema.ResourceData, baremetalAPI *baremetal.API, installServerRequest *baremetal.InstallServerRequest) diag.Diagnostics {
+	installServerRequest.OsID = expandZonedID(d.Get("os")).ID
```
Comment (Codelax) [inline scaleway/helpers_baremetal.go:139]:
```suggestion
	installServerRequest.OsID = expandID(d.Get("os"))
```

File: scaleway/resource_baremetal_server.go [hunk 2]
```diff
@@ -257,27 +265,42 @@ func resourceScalewayBaremetalServerUpdate(ctx context.Context, d *schema.Resour
...
+	if d.HasChanges("ssh_key_ids", "reinstall_on_ssh_key") {
+		if !d.Get("reinstall_on_ssh_key").(bool) && !d.HasChange("os") {
+			diags = append(diags, diag.Diagnostic{
+				Severity: diag.Warning,
+				Summary:  "Changes have been made on your SSH key ID(s)",
+				Detail: "[WARN] This change induce the reinstall of your server. " +
+					"If this behaviour is wanted, please set 'reinstall_on_ssh_key' argument to true",
+			})
+		} else {
+			baremetalInstallServer(ctx, d, baremetalAPI, installReq)
```
Comment (Codelax) [inline scaleway/resource_baremetal_server.go:294]: handle error

File: scaleway/resource_baremetal_server.go [hunk 3]
```diff
@@ -257,27 +265,42 @@ func resourceScalewayBaremetalServerUpdate(ctx context.Context, d *schema.Resour
...
+		ServerID: zonedID.ID,
+		Hostname: expandStringWithDefault(d.Get("hostname"), d.Get("name").(string)),
+	}
 
-		_, err := baremetalAPI.InstallServer(installReq, scw.WithContext(ctx))
-		if err != nil {
-			return diag.FromErr(err)
-		}
+	if d.HasChange("os") {
+		baremetalInstallServer(ctx, d, baremetalAPI, installReq)
```
Comment (Codelax) [inline scaleway/resource_baremetal_server.go:275]: handle error

**Review by Codelax — APPROVED** [review]
