### PR TITLE
fix: add timeout values in schema when they're being used

### LINKED ISSUE #1313: Timeouts other than default cannot be override
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- [ ] scaleway_account_ssh_key
- [x] scaleway_apple_silicon_server
- [x] scaleway_baremetal_server
- [x] scaleway_container_namespace
- [x] scaleway_domain_record
- [ ] scaleway_domain_zone
- [x] scaleway_function_namespace
- [ ] scaleway_instance_ip
- [ ] scaleway_instance_ip_reverse_dns
- [ ] scaleway_instance_volume
- [ ] scaleway_instance_security_group
- [ ] scaleway_instance_security_group_rules
- [x] scaleway_instance_server
- [x] scaleway_instance_snapshot
- [ ] scaleway_instance_placement_group
- [x] scaleway_instance_private_nic
- [ ] scaleway_iot_hub
- [ ] scaleway_iot_device
- [x] scaleway_iot_route
- [x] scaleway_iot_network
- [x] scaleway_k8s_cluster
- [x] scaleway_k8s_pool
- [x] scaleway_lb
- [x] scaleway_lb_ip
- [x] scaleway_lb_backend
- [x] scaleway_lb_certificate
- [x] scaleway_lb_frontend
- [ ] scaleway_lb_route
- [x] scaleway_registry_namespace
- [ ] scaleway_container
- [x] scaleway_rdb_acl
- [x] scaleway_rdb_database
- [x] scaleway_rdb_instance
- [x] scaleway_rdb_privilege
- [x] scaleway_rdb_user
- [x] scaleway_redis_cluster
- [ ] scaleway_object_bucket
- [x] scaleway_vpc_public_gateway
- [x] scaleway_vpc_gateway_network
- [ ] scaleway_vpc_public_gateway_dhcp
- [x] scaleway_vpc_public_gateway_dhcp_reservation
- [ ] scaleway_vpc_public_gateway_ip
- [x] scaleway_vpc_public_gateway_pat_rule
- [ ] scaleway_vpc_private_network

### Terraform Configuration Files

```hcl
resource "scaleway_lb_ip" "ip" {
  zone = "fr-par-1"
}

resource "scaleway_lb" "base" {
  ip_id  = scaleway_lb_ip.ip.id
  zone   = scaleway_lb_ip.ip.zone
  type   = "LB-S"
  timeouts {
  	create = "60m"
  }
}

```

### Expected Behavior

Create timeout should be 60 minutes

### Actual Behavior

```
│ Error: Unsupported argument
│ 
│   on main.tf line 19, in resource "scaleway_lb" "base":
│   19:   	create = "60m"

```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

### PR DESCRIPTION
**Pull request by Codelax**
Fix #1313

### CODE REVIEW

File: scaleway/resource_k8s_pool.go [hunk 1]
```diff
@@ -21,6 +21,8 @@ func resourceScalewayK8SPool() *schema.Resource {
 			StateContext: schema.ImportStatePassthroughContext,
 		},
 		Timeouts: &schema.ResourceTimeout{
+			Create:  schema.DefaultTimeout(defaultK8SPoolTimeout),
```
Comment (Monitob) [inline scaleway/resource_k8s_pool.go:24]: Why is the read missing?

Comment (Codelax) [reply scaleway/resource_k8s_pool.go:24]: It is not used in the resource

**Review by Monitob — APPROVED** [review]

**Review by remyleone — APPROVED** [review]
