### PR TITLE
fix(function): timeout type

### LINKED ISSUE #1476: Resource Function attribute timeout failing
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_function

### Terraform Configuration Files

```hcl
resource scaleway_function main {
  namespace_id = scaleway_function_namespace.main.id
  runtime      = "go118"
  handler      = "Handle"
  privacy      = "private"
  zip_file = "function.zip"
  timeout = "100s"
  zip_hash = filesha256("function.zip")
  deploy = true
}
```

### Debug Output

```
panic: interface conversion: interface {} is string, not int64
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by Codelax**
Fix #1476

### CODE REVIEW

File: scaleway/resource_function_test.go [hunk 1]
```diff
@@ -78,6 +78,41 @@ func TestAccScalewayFunction_Basic(t *testing.T) {
...
+				Config: `
+					resource scaleway_function_namespace main {}
+
+					resource scaleway_function main {
+						name = "foobar"
+						namespace_id = scaleway_function_namespace.main.id
+						runtime = "node14"
+						privacy = "private"
+						handler = "handler.handle"
+						timeout = 10
```
Comment (Monitob) [inline scaleway/resource_function_test.go:100]: Can you add this to the example on the documentation

**Review by remyleone — APPROVED** [review]
