### PR TITLE
fix(iam_api_key): set secret_key on create

### LINKED ISSUE #1490: Resource(iam): secret_key always empty
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_XXXX

### Terraform Configuration Files

```
{
  "access_key" = "XXXXXXXXXXXXX"
  "application_id" = "XXXXXX-XXXXXXXXXX-XXXXXXX"
  "created_at" = "2022-09-30T11:15:52Z"
  "creation_ip" = "77.XXXX.52.240"
  "default_project_id" = "XXXX-XXXXXXXXXXf83d2acb37XX"
  "description" = "XXXXXXXXX"
  "editable" = true
  "expires_at" = ""
  "id" = "SCWEXXXXXXXXXN1H3K6V"
  "secret_key" = ""
  "updated_at" = "2022-09-30T11:15:52Z"
  "user_id" = tostring(null)
}
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by Codelax**
fix #1490

### CODE REVIEW

File: scaleway/resource_iam_api_key_test.go [hunk 1]
```diff
@@ -68,6 +68,7 @@ func TestAccScalewayIamApiKey_WithApplication(t *testing.T) {
 					testAccCheckScalewayIamAPIKeyExists(tt, "scaleway_iam_api_key.main"),
 					resource.TestCheckResourceAttrPair("scaleway_iam_api_key.main", "application_id", "scaleway_iam_application.main", "id"),
 					resource.TestCheckResourceAttr("scaleway_iam_api_key.main", "description", "a description"),
+					resource.TestCheckResourceAttrSet("scaleway_iam_api_key.main", "secret_key"),
```
Comment (Monitob) [inline scaleway/resource_iam_api_key_test.go:71]: Please add this as the last step ```        {
          ResourceName:            resourceName,
          ImportState:             true,
          ImportStateVerify:       true,
          ImportStateVerifyIgnore: []string{"secret_key"},
        },```

**Review by Monitob — CHANGES_REQUESTED** [review]

**Review by Monitob — APPROVED** [review]
