### PR TITLE
fix: optional strings update and skip empty updates

### LINKED ISSUE #1425: Resource update may never apply when removing an updatable attribute from config
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v2.2.7 and below.

### Affected Resource(s)

Every updatable attribute in `UpdateContext` functions where
- `expand<Type>Ptr` is used
- attribute is not required
- attribute does not have default value

### Terraform Configuration Files

```hcl
resource "scaleway_account_project" "prod" {
  name = "prod"
  # description = "blabla" <== remove or comment an updatable field
}
```
### Steps to Reproduce

1. `terraform apply` ==> create the resource
2. Remove updatable attribute from the `.tf` file 
3. `terraform apply` ==> show diff
4. "yes" ==> looks like it's applied
5. `terraform apply` ==> show diff aggain

### Debug Output

Will show this output after every `terraform apply`:

```bash
  # scaleway_account_project.prod will be updated in-place
  ~ resource "scaleway_account_project" "prod" {
      - description     = "blabla" -> null
        id              = "915a76ee-aa03-42e6-a912-8aa61095a271"
        name            = "prod"
        # (3 unchanged attributes hidden)
    }
(prompt "yes")
Apply complete! Resources: 0 added, 5 changed, 0 destroyed.
```

### Expected Behavior

Should not show diff after apply.

### References

In the following example `expandStringPtr` will return `nil`:

```go
// ...
			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Description of the project",
			},
// ...
	if d.HasChange("name") {
		updateRequest.Name = expandStringPtr(d.Get("description"))
	}
```

Fix could be to set a `Default` value in the schema:

```
			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Description of the project",
				Default: "",
			},
```

### PR DESCRIPTION
**Pull request by Codelax**
Fix #1425

### CODE REVIEW

File: scaleway/helpers.go [hunk 1]
```diff
@@ -503,6 +503,10 @@ func expandStringPtr(data interface{}) *string {
 	return scw.StringPtr(data.(string))
 }
 
+func expandUpdatedStringPtr(data interface{}) *string {
+	return scw.StringPtr(data.(string))
```
Comment (kindermoumoute) [inline scaleway/helpers.go:507]: `data` can be nil

```suggestion
	str := ""
	if data != nil {
		str = data.(string)
	}
	return str
```

File: scaleway/resource_iam_group.go [hunk 2]
```diff
@@ -131,8 +131,8 @@ func resourceScalewayIamGroupUpdate(ctx context.Context, d *schema.ResourceData,
 	if d.HasChanges("name", "description") {
 		_, err = api.UpdateGroup(&iam.UpdateGroupRequest{
 			GroupID:     group.ID,
-			Name:        expandStringPtr(d.Get("name").(string)),
-			Description: expandStringPtr(d.Get("description").(string)),
+			Name:        expandUpdatedStringPtr(d.Get("name").(string)),
+			Description: expandUpdatedStringPtr(d.Get("description").(string)),
```
Comment (kindermoumoute) [inline scaleway/resource_iam_group.go:135]: nit

```suggestion
			Name:        expandUpdatedStringPtr(d.Get("name")),
			Description: expandUpdatedStringPtr(d.Get("description")),
```

**Review by kindermoumoute — CHANGES_REQUESTED** [review]

File: scaleway/resource_container_namespace.go [hunk 3]
```diff
@@ -145,8 +145,7 @@ func resourceScalewayContainerNamespaceUpdate(ctx context.Context, d *schema.Res
 	}
 
 	if d.HasChange("description") {
-		description := d.Get("description").(string)
-		req.Description = &description
+		req.Description = expandUpdatedStringPtr(d.Get("description"))
```
Comment (remyleone) [inline scaleway/resource_container_namespace.go:148]: Should we add an `hasChanged = true` here?

File: scaleway/resource_container.go [hunk 4]
```diff
@@ -313,7 +313,7 @@ func resourceScalewayContainerUpdate(ctx context.Context, d *schema.ResourceData
 	}
 
 	if d.HasChanges("description") {
-		req.Description = expandStringPtr(d.Get("description"))
+		req.Description = expandUpdatedStringPtr(d.Get("description"))
```
Comment (remyleone) [inline scaleway/resource_container.go:316]: should we add an `hasChange = true` here?

**Review by remyleone — DISMISSED** [review]

File: scaleway/resource_container_namespace.go (hunk 3 above)
Comment (Codelax) [reply scaleway/resource_container_namespace.go:148]: Only one update request can be made in this function, if we entered it, it is because at least of field has changed anyway

File: scaleway/resource_function_namespace.go [hunk 5]
```diff
@@ -142,7 +142,7 @@ func resourceScalewayFunctionNamespaceUpdate(ctx context.Context, d *schema.Reso
 	}
 
 	if d.HasChange("description") {
-		req.Description = scw.StringPtr(d.Get("description").(string))
+		req.Description = expandUpdatedStringPtr(d.Get("description"))
```
[the remark this answers is not in the document]
Comment (Codelax) [reply scaleway/resource_function_namespace.go:145]: Only one update request can be made in this function, if update was triggered, it is because at least one field has changed

File: scaleway/resource_container.go (hunk 4 above)
Comment (Codelax) [reply scaleway/resource_container.go:316]: Only one update request can be made in this function, if update was triggered, it is because at least one field has changed

**Review by kindermoumoute — APPROVED** [review]
