### PR TITLE
test(cassettes): add custom body matcher

### LINKED ISSUE #1230: Test that you can create two resources with two différent bodies and have go-vcr doing the right match between the two
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_XXXX

### Terraform Configuration Files

```hcl
# Copy-paste the minimal (if possible) terraform configuration to reproduce the bug here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by Codelax**
Fix #1230

### CODE REVIEW

File: scaleway/provider_test.go [hunk 1]
```diff
@@ -52,6 +61,85 @@ func getTestFilePath(t *testing.T, suffix string) string {
 	return filepath.Join(".", "testdata", fileName)
 }
 
+// compareJSONBodies compare two given map that represent json bodies
```
Comment (remyleone) [inline scaleway/provider_test.go:64]:
```suggestion
// compareJSONBodies compare two given maps that represent json bodies
```

**Review by remyleone — APPROVED** [review]
