### PR TITLE
fix(k8s): fix always present auto upgrade requets on update

### LINKED ISSUE #596: scaleway_k8s_cluster_beta auto_upgrade options reset after changing ingress
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- Terraform v0.13.3
- provider.scaleway v1.17.0

### Affected Resource(s)

* scaleway_k8s_cluster_beta

### Terraform Configuration Files

```hcl
resource "scaleway_k8s_cluster_beta" "main" {
  ....
  ingress           = "none"
  auto_upgrade {
    enable                        = true
    maintenance_window_day        = "sunday"
    maintenance_window_start_hour = 7
  }
}
```

### Expected Behavior

auto_upgrade options shouldn't be modified if I update the ingress.

### Actual Behavior

The auto_upgrade is reset to `maintenance_window_day="any"`  and `maintenance_window_start_hour = 0` if I update only the ingress.

### Steps to Reproduce

1. `terraform apply`
The cluster is created with  `maintenance_window_day="sunday"`  and `maintenance_window_start_hour = 7` as I can see those values in the web console
2. change ingress from "none" to "traefik2" and run again `terraform apply`
I can see in the web console that the ingress changed to "traefik2" but the maintenance was reset to "Any" and "0".
3. `terraform apply`
I can see it wants to update `maintenance_window_day="any" -> "sunday"` and  `maintenance_window_start_hour = 0 -> 7`
Applying it gives me traefik2, sunday and 7 in the we web console, so I need to `terraform apply` twice for the change to work correctly.

### PR DESCRIPTION
**Pull request by Sh4d1**
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

Fixes #596

### CODE REVIEW

File: scaleway/resource_k8s_cluster_beta.go [hunk 1]
```diff
@@ -854,11 +854,10 @@ func resourceScalewayK8SClusterBetaUpdate(d *schema.ResourceData, m interface{})
 	if d.HasChange("auto_upgrade.0.enable") {
 		updateRequest.AutoUpgrade.Enable = scw.BoolPtr(d.Get("auto_upgrade.0.enable").(bool))
 	}
-	updateRequest.AutoUpgrade.MaintenanceWindow = &k8s.MaintenanceWindow{}
-	if d.HasChange("auto_upgrade.0.maintenance_window_start_hour") {
+
+	if d.HasChange("auto_upgrade.0.maintenance_window_start_hour") || d.HasChange("auto_upgrade.0.maintenance_window_day") {
```
Comment (remyleone) [inline scaleway/resource_k8s_cluster_beta.go:858]: could you use d.HasChanges to simplify?

**Review by remyleone — APPROVED** [review]
