### PR TITLE
fix(rdb): private network update from ipam service

### LINKED ISSUE #2057: Modify RDB private instance configuration transform it in public instance
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.3
terraform-provider-scaleway 2.24.0

### Affected Resource(s)

* scaleway_rdb_instance

### Terraform Configuration Files

first instanciate a RDB without ip_net field

```hcl
private_network {
    pn_id = data.terraform_remote_state.network.outputs.private_network_id
 }
```

then, add ip_net configuration and apply the modification

```hcl
private_network {
    pn_id = data.terraform_remote_state.network.outputs.private_network_id
    ip_net = "172.16.19.8/22"
 }
```

The bug is also present if if you modify the CIDR in ip_net section on a private instance created with an ip_net value

```hcl
private_network {
    pn_id = data.terraform_remote_state.network.outputs.private_network_id
    ip_net = "172.16.19.8/32"
 }
```

### Expected Behavior

The RDB  is modified with the requested private IP endpoint (ex: 172.16.19.8:5432)

### Actual Behavior

The RDB  is modified with a public IP endpoint (ex: 195.154.196.110:24007)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by Monitob**
close #2057

### CODE REVIEW

File: scaleway/resource_rdb_instance.go [hunk 1]
```diff
@@ -611,16 +611,11 @@ func resourceScalewayRdbInstanceUpdate(ctx context.Context, d *schema.ResourceDa
 			return diag.FromErr(err)
 		}
 
-		// get endpoints to detach. It will handle only private networks
-		endPointsToRemove, err := endpointsToRemove(res.Endpoints, d.Get("private_network"))
```
Comment (Codelax) [inline scaleway/resource_rdb_instance.go:615]: `endpointsToRemove` get the list of endpoints that should be removed, this makes so we don't remove endpoints that should not.
Later on, you changed the loop to delete all endpoints that container a private_network. I don't understand the goal here

Comment (Codelax) [reply scaleway/resource_rdb_instance.go:615]: Maybe the `endpointsToRemove` should just be fixed with new changes to detect.
Also, if you remove it, it becomes unused. Why should we stop using it with the many tests that were made.
https://github.com/scaleway/terraform-provider-scaleway/blob/f52c7bc509522e653724c48df6e53aa4ee202c4f/scaleway/helpers_rdb_test.go#L14-L139

**Review by Codelax — CHANGES_REQUESTED** [review]

File: scaleway/resource_rdb_instance.go (hunk 1 above)
Comment (Monitob) [reply scaleway/resource_rdb_instance.go:615]: This method turns useless in order to check only one private network at once. It's removed on the last commit

**Review by Codelax — APPROVED** [review]
