### PR TITLE
Fix(vpcgw): add zone option to  datasource vpcgw

### LINKED ISSUE #1610: Allow zone argument for VPC Public Gateway data source
Currently, the `scaleway_vpc_public_gateway` data source does not allow passing in `zone` as an argument. Instead, it's parsed from the provider configuration context. See here:

https://github.com/scaleway/terraform-provider-scaleway/blob/59b339598a479e450aee27b5c94533b6b7617f05/scaleway/data_source_vpc_public_gateway.go#L36

This however, makes the data source quite difficult to use if you have VPC Public Gateways defined across multiple zones. Current work-around would be to define separate Scaleway providers with aliases and pass them to the data source as a [meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/resource-provider).

Potential solution: allow users to pass the `zone` via an argument. Relevant code block:

https://github.com/scaleway/terraform-provider-scaleway/blob/59b339598a479e450aee27b5c94533b6b7617f05/scaleway/data_source_vpc_public_gateway.go#L13-L33

### PR DESCRIPTION
**Pull request by Monitob**
Close #1610

### CODE REVIEW

File: scaleway/data_source_vpc_public_gateway.go [hunk 1]
```diff
@@ -15,7 +15,7 @@ func dataSourceScalewayVPCPublicGateway() *schema.Resource {
 	dsSchema := datasourceSchemaFromResourceSchema(resourceScalewayVPCPublicGateway().Schema)
 
 	// Set 'Optional' schema elements
-	addOptionalFieldsToSchema(dsSchema, "name")
+	addOptionalFieldsToSchema(dsSchema, "name", "zone")
```
Comment (remyleone) [inline scaleway/data_source_vpc_public_gateway.go:18]: What is the purpose of this line? zone is already in the schema of `resourceScalewayVPCPublicGateway `

Comment (Monitob) [reply scaleway/data_source_vpc_public_gateway.go:18]: Our data-source helper, `zone` remove the optional flag. We have to precise it if we want to keep it optional. Otherwise we got this error : ```Value for unconfigurable attribute```

**Review by remyleone — APPROVED** [review]
